server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: servico-aluno
          uri: lb://servico-aluno
          predicates:
            - Path=/api/alunos/**
        - id: servico-professor
          uri: lb://servico-professor
          predicates:
            - Path=/api/professores/**
        - id: servico-disciplina
          uri: lb://servico-disciplina
          predicates:
            - Path=/api/disciplinas/**
        - id: servico-matricula
          uri: lb://servico-matricula
          predicates:
            - Path=/api/matriculas/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
