server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: student-service
          uri: lb://student-service
          predicates:
            - Path=/api/alunos/**
        - id: teacher-service
          uri: lb://teacher-service
          predicates:
            - Path=/api/professores/**
        - id: subject-service
          uri: lb://subject-service
          predicates:
            - Path=/api/disciplinas/**
        - id: enrollment-service
          uri: lb://enrollment-service
          predicates:
            - Path=/api/matriculas/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
